### PR TITLE
fix(docs): remove extra space in API docs

### LINKED ISSUE #3210: Extra space after expanding request tabs in API docs
### Describe the issue

Image

### PR DESCRIPTION
**Pull request by starlightknown**
**Before**

image

**After**

image

fixes #3210

### CODE REVIEW

File: components/content/ApiDocee.vue [hunk 1]
```diff
@@ -11,6 +11,11 @@
             allow-try="false"
             regular-font="Public Sans"
             mono-font="Source Code Pro"
+            style="
+                --textarea-height: auto;
+                --textarea-min-height: 100px;
+                --code-block-max-height: 600px;
+            "
```
Comment (brian-mulier-p) [inline components/content/ApiDocee.vue]: put that in the style block below please

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]

File: components/content/ApiDocee.vue (hunk 1 above)
Comment (starlightknown) [reply components/content/ApiDocee.vue]: done
