### PR TITLE
Fix: Sort version numbers in descending order in Migration Guide

### LINKED ISSUE #2872: Sort version numbers in DESC order on Migration Guide component
### Describe the issue

Image

### PR DESCRIPTION
**Pull request by Ayush9026**
Closes #2872 

## Description:
This PR fixes the sorting order of version numbers in the Migration Guide component https://github.com/kestra-io/docs/issues/2872 .
Previously, versions were displayed in ascending order, which made it harder to see the latest changes first.
Now, the versions are sorted in descending order so that the most recent version appears at the top.

Before vs After:

image

Migration Guide

### CODE REVIEW

File: components/content/ChildCard.vue [hunk 1]
```diff
@@ -50,6 +50,29 @@
             .where('path', 'LIKE', `${currentPageSlug}/%`)
             .where('path', 'NOT LIKE', `${currentPageSlug}/%/%`)
             .all()
+            .then(items => {
```
Comment (Piyush-r-bhaskar) [inline components/content/ChildCard.vue]: @Ayush9026 we don't require so much to `SORT` this. please remove everything you added and just add `.order('release', 'DESC')` in new line before  `.all()` and we would be fine with the issue resolution.

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]

File: components/content/ChildCard.vue (hunk 1 above)
Comment (Ayush9026) [reply components/content/ChildCard.vue]: Thanks for the feedback @Piyush-r-bhaskar 🙌  
I’ve removed the manual sorting logic and added `.order('release', 'DESC')` before `.all()` as suggested.  
Let me know if any further changes are needed!

**Review by Piyush-r-bhaskar — APPROVED** [review]
