### PR TITLE
fix(core): enhance link color in FAQ

### LINKED ISSUE #3490: FAQ page links are not styled as links
### Describe the issue

While reading the FAQ page, I noticed there are some unstyled links. I only discovered this because the mouse pointer behavior changes and I can see the link in the bottom corner on hover.

https://github.com/user-attachments/assets/3f77e9c9-d581-415e-8b28-edb9196158e9

I found CSS specifically setting the color the white, but I couldn't easily find why the link styles aren't applied. The [community page](https://kestra.io/community), as an example, uses purple to denote links.

### PR DESCRIPTION
**Pull request by iitzIrFan**
fixes: https://github.com/kestra-io/docs/issues/3490

---
Before:
before

---
After:
after
---

### CODE REVIEW

File: pages/faq.vue [hunk 1]
```diff
@@ -246,9 +246,20 @@ h2 {
 .container {
     color: $white;
 
-    p, ul > li, ol > li, span, a {
+    p, ul > li, ol > li, span {
         color: $white;
     }
+
+    a {
+        color: $purple-35;
```
Comment (Piyush-r-bhaskar) [inline pages/faq.vue]:
```suggestion
        color: var(--ks-content-link)
```

File: pages/faq.vue [hunk 2]
```diff
@@ -246,9 +246,20 @@ h2 {
...
+        text-decoration: none;
+        transition: all 0.2s ease-in-out;
+
+        &:hover {
+            color: lighten($purple-35, 10%);
```
Comment (Piyush-r-bhaskar) [inline pages/faq.vue]:
```suggestion
            color: var(--ks-content-link-hover)
```

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]

File: pages/faq.vue (hunk 2 above)
Comment (iitzIrFan) [reply pages/faq.vue]: missed css var there!

**Review by Piyush-r-bhaskar — APPROVED** [review]
LGTM

**Comment by iitzIrFan** [comment]
Thanks for your review @Piyush-r-bhaskar and @akeller for identifying such minor bug :)
